### ISSUE TITLE
Clarify submission file

### ISSUE THREAD

**Issue by Adman** [robocup-junior/rcj-soccersim#116]
I'm creating this issue so we don't forget about this.

My idea is that teams can submit whole "rcj_soccer_team_blue" controller (with included `team_name.txt`, logo, etc.), so we don't have to bother them with renaming it to `robot.py`.

@mrshu @dbscoach @aquahika What do you think?

**Comment by mrshu** [comment]
@Adman I strongly support this.

The question that comes to my mind is whether we should perhaps use some other name. Otherwise, why choose blue rather than yellow? :slightly_smiling_face:

**Comment by Adman** [comment]
Submission file changed a while ago to `rcj_soccer_team_blue`.
